### ISSUE TITLE
AutoParcel

### ISSUE THREAD

**Issue by hamen** [afcastano/AutoValuePlugin#1]
Hi and congratulations for the useful plugin.
Do you think that this could become compatible also with AutoParcel (https://github.com/frankiesardo/auto-parcel)?
Thank you.

**Comment by afcastano** [comment]
Hi @hamen 
Sorry for the late response,
I will keep this in mind when adding new features, but it definitely could support AutoParcel.
You are welcome to create a pull request. =)

**Comment by vjames19** [comment]
@afcastano I'll try to implement this feature, I would also like to add support to https://github.com/evant/auto-parcel-gson.

**Comment by afcastano** [comment]
@hamen I have merged the pull request created by @vjames19 
I also uploaded the plugin to JetBrains repository, try updating it from IntelliJ and let me know if it works.

Thanks @vjames19 , Awesome work!
