### ISSUE TITLE
Generate static Factory

### ISSUE THREAD

**Issue by PaulWoitaschek** [afcastano/AutoValuePlugin#11]
When I create an autovalue class I usually start with the methods it needs like:

```java
@AutoValue public abstract class Sample {
   
   public abstract double firstValue();
   
   public abstract double secondValue();
   
   public abstract LocalDate myDate();
   
   public abstract int thisConfig();
}
```

Then I build the project and add a static factory method like this:

```java
   public static Sample create(double firstValue, double secondValue, LocalDate myDate, int thisConfig){
      return new AutoValue_Sample(firstValue,secondValue,myDate,thisConfig);
   }
```

It would be great if the plugin could generate the static factory method too and not only the builder.

**Comment by afcastano** [comment]
Yes, can be done. I will add another menu option to generate the factory. I will let you know when its done.

Thanks!

PS: You are welcome to issue a pull request. :)

**Comment by afcastano** [comment]
Hi, I have just published version 0.0.9 which adds functionality to generate the "create" factory method.

There is a new menu action (intention, left click, generate menu) that will generate the static factory.

For different reasons I couldn't generate the "create" method just like you wanted. Instead the method will call internally the builder and construct the Object. Something like this: 

```java 
public static Sample create(double firstValue, double secondValue, LocalDate myDate, int thisConfig){
      return builder()
                  .firstValue(firstValue)
                  .secondValue(secondValue)
                  .myDate(myDate)
                  .thisConfig(thisConfig)
                  .build();
   
}
```

Of course, the build method and the Builder class will be also generated and maintained. I still see benefit on having both when the class is small. For classes with many properties, I recommend generating only the builder method.

You should be able to update the plugin from intelliJ now.

Please let me know if this works for you so I can close the issue.

Thanks!

**Comment by evant** [comment]
I find that the using the create method vs a builder is usually either-or. I think it would make more sense to just create one or the other and possibly have options to switch between the two.

**Comment by PaulWoitaschek** [comment]
What stopped you from building the `create` method without the builder? Using the builder is quite a lot of overhead. [Item #5 ;-)](http://www.informit.com/articles/article.aspx?p=1216151&seqNum=5)

**Comment by afcastano** [comment]
@evant @PaulWoitaschek 
You guys are correct. AutoValue itself discourages the use of both factory and builder at the same time since it won't expose the constructor if the builder is present. 

However there are few cases in which you would like to have both. In our project, old code uses create and we are slowly migrating to factory, so at some point the ValueObject will have both.

So how about this:
 - If you generate create method and builder is not present, it will use the AutoValue constructor.
 - If you generate the create method and the create is present, it will use the builder inside the create method (Just like it is now).
 - If you have already generated the create method using the AutoValue constructor and then generate the builder, it will modify the create method to use the builder instead.

Thanks for your suggestions guys.

I will try to implement this soon, so let me know what you thing of it.

**Comment by evant** [comment]
Sounds good to me, the one other case I can think about is that if you remove the builder it should fix the create method to not use it.

**Comment by afcastano** [comment]
Good point, thanks!

That functionality is included in the version I have just released. =)

Thanks!

**Comment by PaulWoitaschek** [comment]
Thanks, works like a charm!

Is it possible to keep annotations like: 

```java
@AutoValue public abstract class RulerConfig {

   @NonNull public static RulerConfig create(@NonNull String value) {
      return new AutoValue_RulerConfig(value);
   }

   @NonNull public abstract String value();
}

**Comment by afcastano** [comment]
It is definitely possible, but this goes beyond just supporting @NonNull annotation. There are other annotations that could be kept after generation (i.e. @Nullable). Also there are some types that could need a special treatment (Optional, List, etc...) when it comes to default values in the Builder.

Next version of AutoValue will have some improvements regarding some of these: https://github.com/google/auto/blob/auto-value-1.3-rc2/value/CHANGES.md 

I am still thinking what would be the best way of supporting all of this options. Maybe a settings area in which you can select what annotations to preserve when generating or what should be the default value for particular types, but still not sure about it.

Happy to receive any suggestions about it, but I think regarding the particular concern of this issue, we are done.

Please confirm, so I can close it.

Again, thank you very much for your input.
