### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by afcastano** [afcastano/AutoValuePlugin#12]
The code is a mess. It is well covered by tests so should be safe to refactor.
Anything that can give more clarity to it will be welcomed.

**Comment by daveRanjan** [comment]
Hi @afcastano , I will like to refactor code. Do you have any guidelines around it?

**Comment by afcastano** [comment]
Hello! 
Just saw this.
I've been too busy the last few months to work on this, but now I should have some time.

I am putting together some development guidelines. Let me know if you are still interested in the refactor.

Thanks!

**Comment by daveRanjan** [comment]
Hi @afcastano, I am still interested. Let me know how can i help.

**Comment by afcastano** [comment]
Hi @daveRanjan, This is the first cut of the dev guidelines:
https://github.com/afcastano/AutoValuePlugin/blob/master/docs/CONTRIBUTE.md
It includes a tutorial on how to set up the project on IntelliJ and have it ready to go.

The refactor I am looking for is around two classes:
[AutoValueFactory](https://github.com/afcastano/AutoValuePlugin/blob/master/src/com/afcastano/intellij/autovalue/generator/AutoValueFactory.java) and [AutoValueHandler](https://github.com/afcastano/AutoValuePlugin/blob/master/src/com/afcastano/intellij/autovalue/generator/AutoValueHandler.java).
I think they have mixed responsibility and the boundaries are not clear. Also there is a bit of duplicated code and long methods.

Thank you very much!

**Comment by daveRanjan** [comment]
Hi @afcastano, I have send a pull request after making changes. Please review.

**Comment by afcastano** [comment]
Great!
Let me take a look and will come back to you!
Thanks for doing this man!

**Comment by afcastano** [comment]
Excellent man! Thank you very much!
I have merged the pull request. You have helped a lot!

I am going to close the issue now!
