### ISSUE TITLE
ArrayIndexOutOfBoundsException when using on classes without abstract methods

### ISSUE THREAD

**Issue by blipinsk** [afcastano/AutoValuePlugin#13]
If you try to use the plugin on a class without any `abstract` methods, e.g. like this:

    @AutoValue
    abstract class Test{
    }

plugin will throw an uncaught `ArrayIndexOutOfBoundsException`.

![ArrayIndexOutOfBoundsException](https://cloud.githubusercontent.com/assets/6371716/17106051/1baf9ecc-528a-11e6-9851-58ea2c599d83.png)

**Comment by afcastano** [comment]
Wow... thanks. I thought I had that covered.
I will fix it a soon as possible

**Comment by afcastano** [comment]
@blipinsk Hi, I have released version 0.0.10 which fixes this bug. You should be able to download it from JetBrains repo now.

Thanks for reporting this.

Let me know if the bug gets fixed.

**Comment by blipinsk** [comment]
Yep the issue seems fixed in the new version, thanks!
