### ISSUE TITLE
Should Ignore toBuilder() methods

### ISSUE THREAD

**Issue by evant** [afcastano/AutoValuePlugin#15]
You can create a `toBuilder()` method to convert your value class back into a builder with it's properties already set. https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#-initialize-a-builder-to-the-same-property-values-as-an-existing-value-instance

The builder and factory method generator should ignore this method.

**Comment by afcastano** [comment]
Hello!
This is implemented in version 1.0.0 
I have submitted the file to jetBrains and it takes up to two days for them to approve it. 
I'll let you know.

Sorry for the delay. I was to busy to work on this the last months, I hope this is still of any value for you.

Thanks.

**Comment by afcastano** [comment]
FYI, Jetbrains has approved the file. Now you can update to version 1.0.0 which fixes this issue. Let me know if it works so I can close this.

**Comment by evant** [comment]
Hm, it looks like it only works if the method is named `toBuilder()`. Note: autovalue doesn't care what the method is named. Is there a way to check the return value instead?

**Comment by afcastano** [comment]
Oh... didn't know that!
Yes... should be easy to fix.
I'll let you know!

**Comment by afcastano** [comment]
The method is ignored based on the return type name. It has to be Builder.
There is the chance the user has another static Builder class, so one improvement will be to compare it with the fully qualified method. I will investigate how likely is this to happen.
