### ISSUE TITLE
Add support for AutoValueGson

### ISSUE THREAD

**Issue by eliasbagley** [afcastano/AutoValuePlugin#22]
AutoValueGson (https://github.com/rharter/auto-value-gson) is a popular AutoValue plugin that would be a perfect fit for this library, since for each class you need to add a boilerplate type adapter method to each class, like:

```
    public static TypeAdapter<MyClass> typeAdapter(Gson gson) {
        return new AutoValue_MyClass.GsonTypeAdapter(gson);
    }
```

It would be great to have the plugin generate this method, like it does for the builder.

**Comment by vanniktech** [comment]
Same goes for auto-value-moshi

**Comment by blipinsk** [comment]
There are multiple popular and good extensions. Adding support for all of those seems like an overkill to me. But maybe thats just me... 😄

**Comment by vanniktech** [comment]
In order to not bloat up the window with the possible extensions it'd be handy if the plugin could detect whether the specific autovalue plugin is on the classpath or not. Given that I'm only using auto-value-moshi as an extension, I don't want to see the gson entry for generating the boiler plate.

**Comment by afcastano** [comment]
Hello guys,
I'll try to see if I can detect plugins in the class path and add the corresponding option to the menu, as @vanniktech suggested.
I will let you know!
Thanks for the suggestion!

**Comment by eliasbagley** [comment]
In the meantime, I'm using this live template:

```
public static TypeAdapter<$CLASS_NAME$> typeAdapter(Gson gson) {
    return new AutoValue_$CLASS_NAME$.GsonTypeAdapter(gson);
}
```
where the `$CLASS_NAME$` variable is set to the built in function `className()`

**Comment by afcastano** [comment]
Hello,
After a second thought, I have found that each extension will have its own caveats and restrictions when generating the methods, so I think pursuing this would be too much for this plugin.

What we can do is create another plugin for each one of the extensions, so people can install the plugin according to the extension they are using. The plugin would be in a different repo and can be tuned up for the specifics of that extension.
