### ISSUE TITLE
doesnt work in android studio 2.1

### ISSUE THREAD

**Issue by uddyami** [afcastano/AutoValuePlugin#8]
After i right click with this code, the autovalue option is disabled
```
@AutoValue public abstract class Order {
  public abstract OrderType orderType();
    public abstract String id();
    public abstract String orderNumber();
}
```

**Comment by afcastano** [comment]
Thanks mate...
I will take a look at it and let you know...
=)

**Comment by afcastano** [comment]
Hi, 
I just tried it and it works normally.

Please be sure that you have the autovalue library in your classpath and also that you are making right-click inside the class.

If still happens, could you send me log generated by Android-studio?

Thanks!

**Comment by gostik** [comment]
For me too:
my file is:
@AutoValue
public abstract class SignUpResponse implements Parcelable {

    public abstract String imgurl();

    public abstract long userid();

    public abstract String fbuser();

    public abstract boolean success();

    public abstract String msg();

    public abstract String fbid();

    public abstract String username();

}

Log:
13:11:45 EmptyThrowable: Null child action in group AutoValue (null) of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=com.afcastano.intellij.autovalue.AddMissingMethodsToBuilderAction

**Comment by afcastano** [comment]
Hi,
I have been reading and it seems that sometimes this error is caused by the JVM version intelliJ is running on. This plugin is compiled using version 1.7 

Could you tell me what JVM version is your Android Studio running on?

(In intelliJ, the JVM version is shown in the About dialog. I imagine it would be the same in Android studio.)

**Comment by gostik** [comment]
Hi, yes 
JRE is 1.6
JDK is 1.8

**Comment by afcastano** [comment]
That might be it.

Could you upgrade the JRE of android-studio to 1.7 or higher?
This is how you could do it: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

Mine is version 1.8 and it works ok.
<img width="401" alt="screen shot 2016-05-18 at 9 36 24 pm" src="https://cloud.githubusercontent.com/assets/3589427/15357267/14f7fd28-1d41-11e6-8069-338421a76cdf.png">

Please let me know if that fixes the problem.

**Comment by gostik** [comment]
Yes, now it works! Thank you!

**Comment by afcastano** [comment]
@gostik Great!!

@uddyami does it fix it for you too?

**Comment by uddyami** [comment]
i couldn't change JDK for studio 2.1 sadly but new android 2.2 preview has jdk 1.8 , so all is good. Thank you.
